### ISSUE TITLE
Why does the API return a 500 when querying a book that has not been released?

### ISSUE THREAD

**Issue by Neurrone** [laxamentumtech/audnexus#239]
https://api.audnex.us/books/B09P3VZGZX returns a 500, although the information for this book is in the Audible API.

**Comment by djdembeck** [comment]
Because Audible typically does not have all data available before the release date (chapters, image, cast, description, runtime, etc), there's no point allowing it to ingest.

**Comment by Neurrone** [comment]
Ah, good point. Perhaps the example that I saw was the exception where it has this information available.
