### ISSUE TITLE
iTunes Hi-Res Cover Art

### ISSUE THREAD

**Issue by csandman** [laxamentumtech/audnexus#244]
Hey, first of all, love the direction that this project is going in!  I think it has a lot of potential for the Plex agent aspect of it.

I've been working on my own audiobook project for a while, a self hosted server for downloading books you have checked out on OverDrive, and your library from Audible.  It also scrapes metadata from Audible, and cover art from iTunes, merges the OverDrive books into a single, properly tagged M4B file, and cracks the DRM on the Audible books, also converting them to M4B (and retagging them so they're in the same format).  The project isn't open source because its kind of in a legal gray area but I could add you as a viewer if you'd like to check out the source, It's entirely written in JS and could offer some ideas.

Anyway, what I was getting at was that the iTunes API offers the highest resolution covers for audiobooks from pretty much any source, and its free to use.  I originally happened upon this when I found the [iTunes Artwork Finder](https://bendodson.com/projects/itunes-artwork-finder/) from [Ben Dodson](https://github.com/bendodson).  If you properly manipulate the URL format for the images it returns, you can get the highest resolution version they have available, anywhere from 1000x1000px to 3000x3000px with the latter being the most common.  These covers easily beat out the measly 500x500px covers offered by Audible and look way better on something like Plex.

I extracted all of the code I use in my project for searching the API, matching the book, and converting the cover link and put it all in a Gist so you can check it out: https://gist.github.com/csandman/0615901502012976122a10b3b2db161f

There are a couple things to note when using this API.  One is that occasionally the link for the cover will fail with a server error, but I've never actually encountered this when using the API programmatically, only in browser, and reloading the page has always fixed the problem. The other is that very rarely the cover image the API returns won't be a perfect square, but will be something very close, so for my project I run a resizing script on them to make both dimensions match the smaller dimension.  They've never been off by enough to make the covers look stretched after resizing.  I included those scripts as a separate file in my Gist in case you're curious.

Anyway, I hope you'll consider adding this.  Its one of the few things I'm really anal about with my audiobooks, making sure the covers look nice.  And if you have any questions about using this (or want to be added to my project) definitely let me know!

**Comment by djdembeck** [comment]
Thanks for dropping by!

Audnexus uses the un-cropped Audible covers, which vary from 1024x1024->3200x3200. Using iTunes as an additional datasource is something I've not thought of - what's their book library like?

**Comment by csandman** [comment]
Overall I've found it to be on par with Audible's, pretty much everything I've found on Audible I've been able to find a match for on iTunes, however my matching function between the two sources is not perfect.  They also sometimes offer alternative covers which can be a nice option for variety.  I wasn't sure how I thought this could be integrated into this project exactly, but I figured its at least a good option to consider.

Also I had never found a way to get a higher resolution version of the Audible covers, so that may very well make the iTunes solution redundant. I'd have to do some comparison on the resulting images to see if one source or the other is more consistent with the higher resolutions, or if they're relatively the same.

**Comment by csandman** [comment]
So I just did a test on [a random book](https://www.audible.com/pd/Warriors-Super-Edition-Crookedstars-Promise-Audiobook/006307463X) and saw that the Audible API returns a 2400x2400 image and the iTunes API returns a 3000x3000 image.  This isn't a huge difference resolution wise, but the main difference is the level of compression. While the Audible image has a large resolution, the file is only 299 KB where as the iTunes image is 2.8 MB:

Audible: https://m.media-amazon.com/images/I/81by7prwbcS.jpg
iTunes: http://is5.mzstatic.com/image/thumb/Music115/v4/97/58/fb/9758fbb7-b592-698a-c23d-99282b1f6e0a/9780063074637.jpg/100000x100000-999.jpg

So if you're looking for the best quality image available, I'd say that the iTunes one is most likely going to be far less compressed, but there is the tradeoff in terms of storage.
