### ISSUE TITLE
Please add AudiobookGuild catalog to the audnexus db.

### ISSUE THREAD

**Issue by Emasoft** [laxamentumtech/audnexus#407]
Please add AudiobookGuild catalog to the audnexus db. 
Audible had been abandoned by many important authors. The new rising publisher is AudiobookGuild, and most of the new audiobooks are exclusively on their platform. Not even on Amazon.
For example the popular series "Summoner" by Eric Vall is only available till volume 16 on Audible. If you want volume 17 to 22, you can only find them on AudiobookGuild. 
If I search for metadata for Summoner 22, I cannot find any result because it is not even on Audible. But the metadata is there on AudiobookGuild (see: https://audiobookguild.com/collections/summoner-by-eric-vall/products/summoner-22 ). 
Can you add it?

**Comment by djdembeck** [comment]
You can add these to AudiobookDB when it opens.
