### ISSUE TITLE
make "https://api.audible.*" configurable

### ISSUE THREAD

**Issue by lduesing** [laxamentumtech/audnexus#494]
As I learned today, every audible domain has its own catalog, so some titles are not available in other languages (I think trading rights are in the way..) 
So it would be nice to allow asking other domains, maybe at first via environment variables, but in the long run like https://api.audnex.us/de/books (and with https://api.audnex.us/books referring to https://apt.audnex.us/com/books for compatibility)

**Comment by djdembeck** [comment]
This is something I want to add soon. There are a handful of blockers currently:
- need to add a `region` field to models and update all existing ones to use `us`.
- authors would likely duplicate themselves unless we add `region` field to those too.
- English-specific helpers, such as `chapterTitleCleanup` would need to be disabled or updated with translations for each region.
- URL would either need to be changed, as you mentioned or query param such as `?region=de` used.

That said, I don't think this is *particularly* hard to accomplish; just some thought needs to be put into it.

**Comment by djdembeck** [comment]
Closing in favor of existing issue: https://github.com/laxamentumtech/audnexus/issues/72
