### ISSUE TITLE
Incorrect interpretation of genre/tags from the "Audible.de" website

### ISSUE THREAD

**Issue by Hallo951** [laxamentumtech/audnexus#517]
Hello, I use the [audiobookshelf](https://github.com/advplyr/audiobookshelf)  programme to manage audiobooks. This in turn uses the Audnexus software for scraping the metadata for the audiobooks from the website audible.de or audible.com and various other languages. Unfortunately, Audnexus misinterprets the genre and tags on, for example, audible.de. Here I have described the problems in detail with screenshots.

Here the link: [[Bug]: Incorrect transfer of genres and tags when scraping with audible (all variants)](https://github.com/advplyr/audiobookshelf/issues/1093)

**Comment by djdembeck** [comment]
I see the problem - another `.com` specific portion of checks for genres. I'll work on a patch for this.

**Comment by Hallo951** [comment]
Thanks...

**Comment by Hallo951** [comment]
When will you release the update?

**Comment by djdembeck** [comment]
> When will you release the update?

Updates to our public server are published when a release is merged into the `main` branch. You are free to create your own API instance and use the `develop` branch to get updates faster
