### ISSUE TITLE
Only 500 Internal Server Error

### ISSUE THREAD

**Issue by 9Mad-Max5** [laxamentumtech/audnexus#543]
I always get this message.

https://api.audnex.us/books/B004V3F0RK
{"statusCode":500,"error":"Internal Server Error","message":"Required key 'authors' does not exist in Audible API response for ASIN B004V3F0RK"}

It seems to me the whole api is completley down even if the Status page tells sth different.

**Comment by djdembeck** [comment]
The error means what you requested doesn't have enough data to parse. The title you linked is probably missing some data as it was removed: https://www.audible.com/pd/B004V3F0RK
