### ISSUE TITLE
Using region "au", book is not returning

### ISSUE THREAD

**Issue by jberlyn** [laxamentumtech/audnexus#571]
I am using the Audnexus API (through the Audiobookshelf server application) and it is not returning specific books. I can get the book to return correctly through the Audible API, but using the ASIN provided by the Audible API with the Audnexus API, is returning a 500.

Here are the two calls:

Audible API
https://api.audible.com.au/1.0/catalog/products?title=nolyn

Audnexus API
https://api.audnex.us/books/B089XC53RW?region=au

I initially opened an issue on the Audiobookshelf github page but the problem was narrowed down to Audnexus.

https://github.com/advplyr/audiobookshelf/issues/1191

**Comment by djdembeck** [comment]
The issue was caused by `.com.au` using 10 digit genre ASINs instead of 11 digit (which is used everywhere else afaik).

Thanks for the report!
