### ISSUE TITLE
audiobooks from audible.de (german audible) has sometime  no series data

### ISSUE THREAD

**Issue by christopherpross** [laxamentumtech/audnexus#589]
Hey,

nice project, thanks for that!

Some audiobooks from audible.de in the audnex-API (public) has no series data. The json-element doesn't exist.

Here are two books that are working and two that aren't working.
Is this a problem off audible? I think not, because the series data is visible on the normal audible website.

## Working audiobooks
* [audible link](https://www.audible.de/pd/Leviathan-erwacht-The-Expanse-Serie-1-Hoerbuch/B07CSV7QB1?plink=2BN8anX5j42h6HBK&ref=a_hp_c3_adblp13ntbpr_1_2&pf_rd_p=4025b596-0df8-4638-affc-fcdac9c64b68&pf_rd_r=JXHX4AVSQYKDCXXZ5TAD&pageLoadId=VtFiVVJ7BvKRGCy3&creativeId=ad854ef3-cb1d-4831-8dfa-fb10760746f5) - [API Request](https://api.audnex.us/books/B07CSV7QB1?region=de)
* [audible link](https://www.audible.de/pd/Harry-Potter-und-der-Stein-der-Weisen-Gesprochen-von-Rufus-Beck-Hoerbuch/B01M02FJ7A?qid=1679686026&sr=1-7&ref=a_search_c3_lProduct_1_7&pf_rd_p=e54013e2-074a-460e-861f-7feac676b789&pf_rd_r=QXZ4E3PPHRFPKPVC779X&pageLoadId=HAJlS57lBAM7BWDE&creativeId=41e85e98-10b8-40e2-907d-6b663f04a42d) - [API Request](https://api.audnex.us/books/B01M02FJ7A?region=de)

## not working
* [audible link](https://www.audible.de/pd/9-Tot-am-Bueffet-Hoerbuch/B0BWF5H1QY?ref=a_hp_c11_product_1_1&pf_rd_p=589f86ce-4fa6-45bf-87e7-6b9063d2d280&pf_rd_r=JXHX4AVSQYKDCXXZ5TAD&pageLoadId=VtFiVVJ7BvKRGCy3&creativeId=479e239f-d883-4ad2-b4b1-d5ba113f9425) - [API Request](https://api.audnex.us/books/B0BWF5H1QY?region=de)
* [audible link](https://www.audible.de/pd/Very-Bad-Liars-Hoerbuch/B0BYK2DH9Q?ref=a_newreleas_c3_lProduct_1_20&pf_rd_p=900a9ba5-8f98-47da-9a0d-429fe6167612&pf_rd_r=2K1CCDH6DRV8AD83985X&pageLoadId=VL9EGLUx8IL5hyXR&creativeId=b5ae74b6-b8fa-4066-8bf9-0486afafaa5b) - [API Request](https://api.audnex.us/books/B0BYK2DH9Q?region=de)
* [audible link](https://www.audible.de/pd/Philadelphia-Pucks-Braden-Jocelyn-Hoerbuch/B0BYZCMTDL?ref=a_newreleas_c3_lProduct_2_6&pf_rd_p=900a9ba5-8f98-47da-9a0d-429fe6167612&pf_rd_r=H2VP17M2TEJ4NNSKDKG7&pageLoadId=2sWIh1LefA9MT1UJ&creativeId=b5ae74b6-b8fa-4066-8bf9-0486afafaa5b) - [API Request](https://api.audnex.us/books/B0BYZCMTDL?region=de)

I hope you can use the sample books, when you need more, I can try to find some and add it here.

**Comment by djdembeck** [comment]
This seems like an inconsistency on Audible's side. They have the books that are missing series, listed as a SinglePartBook, instead of MultiPartBook. I'll see if I can find a good way around this without loosing our data checking process.
