### ISSUE TITLE
Region is ignored for /authors

### ISSUE THREAD

**Issue by lukeIam** [laxamentumtech/audnexus#609]
Example:
"Jussi Adler-Olsen": "B0043BVIJE"

https://api.audnex.us/authors/B0043BVIJE?region=de
=> returns an English description 

https://www.audible.de/author/Jussi-Adler-Olsen/B0043BVIJE
=> Audible has a German description

**Comment by djdembeck** [comment]
Hello, the issue is some author pages weren't able to be scraped correctly until https://github.com/laxamentumtech/audnexus/commit/ddf2d22f46cd3bfa2f9cbce7e8725d445db74b6e

I'm updating these in the database now, to force re-pulling the correct pages.
