### ISSUE TITLE
Question: Can we achieve community metadata refinements?

### ISSUE THREAD

**Issue by remmycat** [laxamentumtech/audnexus#638]
I sometimes like to manually fix the metadata I receive from Audible (and thus audnexus), like titles, series information, chapters (splits and names) for books I own, but have nowhere to put the resulting work other than my personal library. I would love to have a place where I can share this with the public, and receive community metadata improvements myself.

I'm currently using audnexus for getting audiobook metadata and was wondering if the wish for community overwrites could be realised as a complementary project, or if people have some other helpful input.

I'm imagining a database of refined community metadata, that's not just an independently collected metadata database, but uses already aggregated publisher metadata (e.g. via audnexus) as a basis, to then add select refinements and fixes to align the original data with some explicit community standards (how to name and split chapters, how to tag a book series, ...).

This could possibly work with diffs based on existing data, that can be invalidated in some way when the source changes.

So, I have a few questions:
> (!) To make it clear: I'm very much not meaning to demand anyone spending work on answering these ideas of mine. Let me know if this shouldn't be an issue / if I should move this somewhere else.)

1. Would you want this to be "part of audnexus" at all, or would you see this more as a project that could build on top of the data audnexus provides but should be kept separate?
1. Can you think of any special requirements on such a database, so it could easily be integrated with audnexus (either directly or in a separate project)? Do you think the diff suggestion makes sense here?
1. What do you think would be the easiest way to manage this kind of database? I'm thinking a public Github repo, and maybe a simple static website that lets people load and edit source metadata to generate a diff and a PR.
1. Does someone maybe know of existing projects of the same type, that should receive help instead of putting energy into building something similar?

**Comment by djdembeck** [comment]
There were plans for AudiobookDB (https://github.com/djdembeck/djdembeck/issues/2), until a collaborator who committed to frontend, stopped responding to me.

The project is now in limbo, until I can muster up the time to learn Svelte's frontend concepts.

**Comment by remmycat** [comment]
Thanks for the info!

I realised now that some existing open audiobook metadata database projects are probably what I was looking for, and where I can maybe support for now, so I'm gonna look into those and will close this issue 🙂
