### ISSUE TITLE
Failed to get chapters for books released in the last few month

### ISSUE THREAD

**Issue by JaegerMaster** [laxamentumtech/audnexus#658]
Most of the time, the chapter endpoint leads to 404 error. Not sure if this is an aduble issue or not, as it started happening only a few days ago.

Example URL:

https://api.audnex.us/books/B0BLJ78Y1Y/chapters: status code 404, Not Found

**Comment by djdembeck** [comment]
Thank you for filing this - I've noticed this issue on a handful of books as well. We recently merged a chapters change, which is likely to be a factor.

I'll look into this and maybe get a patch up soon.

**Comment by djdembeck** [comment]
Taking a further look into this, it seems to be an Audible issue:
`https://api.audible.com/1.0/content/B0BSLV7WV8/metadata?response_groups=chapter_info`
```
{
    "message": "Generic error encountered while performing client evaluation for allowed consumption types."
}
```

**Comment by JaegerMaster** [comment]
I think this issue has cropped up again:

`Error while requesting https://api.audnex.us/books/B0CHSDFBB1/chapters: status code 404, Not Found`

**Comment by TaroAM** [comment]
`Error while requesting https://api.audnex.us/books/B07XTMQ66Y/chapters: status code 404, Not Found 
`
Thought it was release date but this was out in 2019 and still has the same error
