### ISSUE TITLE
Question: Updated covers on Audible

### ISSUE THREAD

**Issue by tehguitarist** [laxamentumtech/audnexus#735]
Hi there,

Love the project, just had a question around audible books with updated covers.

It seems like books with recently updated covers are still pulling the old covers. An example of this is:
https://www.audible.com.au/pd/Homeland-Audiobook/B00FMUW24K
https://api.audnex.us/books/B00FMUW24K?region=au

Just checking if this is just how Audible is reporting back, or if something needs to be tweaked?

I've checked this on US based audible books too.

**Comment by IgnisDa** [comment]
You need to pass the `update` query parameter. `https://api.audnex.us/books/B00FMUW24K?region=au&update=1`.

**Comment by tehguitarist** [comment]
Thanks so much, that does the trick!
